# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='external_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
