# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='cloudId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
