# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cloud',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Cloud'),
            preserve_default=False,
        ),
    ]
