# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_instance_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='cloudId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('name', 'cloud'), ('cloud', 'cloudId')]),
        ),
    ]
