# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161116_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True),
        ),
    ]
