# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20161116_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set([('user', 'image'), ('cloud', 'computeId')]),
        ),
    ]
